"use client";

import type { WorkspaceFrameProps } from "./studio-workspace-frame";
import { StudioWorkspaceFrame } from "./studio-workspace-frame";

export type WorkspacePaneProps = WorkspaceFrameProps;

export function StudioWorkspacePane({
  pageNum,
  zoom,
  pan,
  activeMode,
  componentAuthoringMode,
  wireAuthoringMode,
  cableAuthoringMode,
  tool,
  snapStrength,
  selectedBox,
  selectedAttachment,
  selectedBoxId,
  yoloBulkSelectedBoxIds,
  selectedAttachmentId,
  boxesForPage,
  relationshipHighlights,
  datasetClassHighlight,
  connectionPointEditor,
  connectorTerminalPrompt,
  componentLabelPrompt,
  connectionPointEditorTarget,
  overlayLabels,
  draftBox,
  imageSrc,
  imageStatus,
  cursorPx,
  symbolBankStatus,
  metadataStatus,
  annotationStatus,
  relationNotice,
  overlayPillsVisible,
  yoloAnnotationsVisible,
  yoloHumanAnnotationsVisible,
  exportYolov26Url,
  exportGoogleObjectDetectionUrl,
  exportQwen3vlColabDatasetUrl,
  typeMenuAttachmentId,
  typeMenuBoxId,
  onPreviousPage,
  onNextPage,
  onZoomIn,
  onZoomOut,
  onResetView,
  onModeChange,
  onComponentAuthoringModeChange,
  onWireAuthoringModeChange,
  onCableAuthoringModeChange,
  onToolChange,
  onSnapStrengthChange,
  onSnapSelected,
  onCycleLabelCandidate,
  onSavePage,
  onDetectYoloPage,
  yoloTool,
  onYoloToolChange,
  onYolov26DetectSettingsChange,
  yolov26DetectSettings,
  onClearYoloPage,
  onClearYoloAiPage,
  onClearYoloHumanPage,
  setSelectedBoxId,
  setSelectedAttachmentId,
  setTypeMenuAttachmentId,
  setTypeMenuBoxId,
  setOverlayPillsVisible,
  setYoloAnnotationsVisible,
  setYoloHumanAnnotationsVisible,
  setConnectionPointEditor,
  setConnectorTerminalPrompt,
  setComponentLabelPrompt,
  onConfirmConnectorTerminalPrompt,
  onCancelConnectorTerminalPrompt,
  onConfirmComponentLabelPrompt,
  onCancelComponentLabelPrompt,
  onChangeRootType,
  onChangeAttachmentType,
  onCommitConnectionPointEditor,
  onCancelConnectionPointEditor,
  onUndo,
  setCursorPx,
  setHoverStack,
  hoverStackCyclingRef,
  hoverStackIndexRef,
  stageRef,
  stageHandlers,
  boxHandlers,
  onChangeImageReady,
  onChangeImageError,
  annotationWorkspaceMode,
  onAnnotationWorkspaceModeChange,
  children,
}: WorkspacePaneProps) {
  return (
    <StudioWorkspaceFrame
      annotationWorkspaceMode={annotationWorkspaceMode}
      pageNum={pageNum}
      zoom={zoom}
      pan={pan}
      activeMode={activeMode}
      componentAuthoringMode={componentAuthoringMode}
      wireAuthoringMode={wireAuthoringMode}
      cableAuthoringMode={cableAuthoringMode}
      tool={tool}
      snapStrength={snapStrength}
      selectedBox={selectedBox}
      selectedAttachment={selectedAttachment}
      selectedBoxId={selectedBoxId}
      yoloBulkSelectedBoxIds={yoloBulkSelectedBoxIds}
      selectedAttachmentId={selectedAttachmentId}
      boxesForPage={boxesForPage}
      relationshipHighlights={relationshipHighlights}
      datasetClassHighlight={datasetClassHighlight}
      connectionPointEditor={connectionPointEditor}
      connectorTerminalPrompt={connectorTerminalPrompt}
      componentLabelPrompt={componentLabelPrompt}
      connectionPointEditorTarget={connectionPointEditorTarget}
      overlayLabels={overlayLabels}
      draftBox={draftBox}
      imageSrc={imageSrc}
      imageStatus={imageStatus}
      cursorPx={cursorPx}
      symbolBankStatus={symbolBankStatus}
      metadataStatus={metadataStatus}
      annotationStatus={annotationStatus}
      relationNotice={relationNotice}
      overlayPillsVisible={overlayPillsVisible}
      yoloAnnotationsVisible={yoloAnnotationsVisible}
      yoloHumanAnnotationsVisible={yoloHumanAnnotationsVisible}
      exportYolov26Url={exportYolov26Url}
      exportGoogleObjectDetectionUrl={exportGoogleObjectDetectionUrl}
      exportQwen3vlColabDatasetUrl={exportQwen3vlColabDatasetUrl}
      typeMenuAttachmentId={typeMenuAttachmentId}
      typeMenuBoxId={typeMenuBoxId}
      onPreviousPage={onPreviousPage}
      onNextPage={onNextPage}
      onZoomIn={onZoomIn}
      onZoomOut={onZoomOut}
      onResetView={onResetView}
      onModeChange={onModeChange}
      onComponentAuthoringModeChange={onComponentAuthoringModeChange}
      onWireAuthoringModeChange={onWireAuthoringModeChange}
      onCableAuthoringModeChange={onCableAuthoringModeChange}
      onToolChange={onToolChange}
      onSnapStrengthChange={onSnapStrengthChange}
      onSnapSelected={onSnapSelected}
      onCycleLabelCandidate={onCycleLabelCandidate}
      onSavePage={onSavePage}
      onDetectYoloPage={onDetectYoloPage}
      yoloTool={yoloTool}
      onYoloToolChange={onYoloToolChange}
      onYolov26DetectSettingsChange={onYolov26DetectSettingsChange}
      yolov26DetectSettings={yolov26DetectSettings}
      onClearYoloPage={onClearYoloPage}
      onClearYoloAiPage={onClearYoloAiPage}
      onClearYoloHumanPage={onClearYoloHumanPage}
      onUndo={onUndo}
      onChangeRootType={onChangeRootType}
      onChangeAttachmentType={onChangeAttachmentType}
      onCommitConnectionPointEditor={onCommitConnectionPointEditor}
      onCancelConnectionPointEditor={onCancelConnectionPointEditor}
      setSelectedBoxId={setSelectedBoxId}
      setSelectedAttachmentId={setSelectedAttachmentId}
      setTypeMenuAttachmentId={setTypeMenuAttachmentId}
      setTypeMenuBoxId={setTypeMenuBoxId}
      setOverlayPillsVisible={setOverlayPillsVisible}
      setYoloAnnotationsVisible={setYoloAnnotationsVisible}
      setYoloHumanAnnotationsVisible={setYoloHumanAnnotationsVisible}
      setConnectionPointEditor={setConnectionPointEditor}
      setConnectorTerminalPrompt={setConnectorTerminalPrompt}
      setComponentLabelPrompt={setComponentLabelPrompt}
      onConfirmConnectorTerminalPrompt={onConfirmConnectorTerminalPrompt}
      onCancelConnectorTerminalPrompt={onCancelConnectorTerminalPrompt}
      onConfirmComponentLabelPrompt={onConfirmComponentLabelPrompt}
      onCancelComponentLabelPrompt={onCancelComponentLabelPrompt}
      setCursorPx={setCursorPx}
      setHoverStack={setHoverStack}
      hoverStackCyclingRef={hoverStackCyclingRef}
      hoverStackIndexRef={hoverStackIndexRef}
      stageRef={stageRef}
      stageHandlers={stageHandlers}
      boxHandlers={boxHandlers}
      onChangeImageReady={onChangeImageReady}
      onChangeImageError={onChangeImageError}
      onAnnotationWorkspaceModeChange={onAnnotationWorkspaceModeChange}
    >
      {children}
    </StudioWorkspaceFrame>
  );
}
